### ISSUE TITLE
example files

### ISSUE THREAD

**Issue by andrewdavis3** [mickaelsilva/chewBBACA#1]
Looks like your still developing but do you happen to have example files for for "listGenomes.txt" and "listGenes.txt" I keep getting the "ERROR! AT LEAST ONE GENE FILE MUST CONTAIN AN ALLELE REPRESENTING A CDS" message.

**Comment by mickaelsilva** [comment]
a listgenomes example should be like:

> /home/user/genomes/genome1.fasta
> /home/user/genomes/genome2.fasta

you could use the following example bash command
`find /home/user/genomes/*.fasta >listGenomes.txt`

the input genomes need to be previously assembled

**Comment by andrewdavis3** [comment]
my listgenome.txt is just a contig file chewBBACA/test_contigs.fasta

my listgene.txt is the files in the short folder:
chewBBACA/schema_seed/gi_57158257_dbj_AP006725.1_:1002380-1003105_short.fasta
chewBBACA/schema_seed/gi_57158257_dbj_AP006725.1_:1003225-1004076_short.fasta
chewBBACA/schema_seed/gi_57158257_dbj_AP006725.1_:1004227-1004952_short.fasta
chewBBACA/schema_seed/gi_57158257_dbj_AP006725.1_:1005103-1005660_short.fasta
chewBBACA/schema_seed/gi_57158257_dbj_AP006725.1_:1005889-1007091_short.fasta
chewBBACA/schema_seed/gi_57158257_dbj_AP006725.1_:1007329-1008087_short.fasta
chewBBACA/schema_seed/gi_57158257_dbj_AP006725.1_:1008100-1008957_short.fasta

Do I need more than one genome?

**Comment by mickaelsilva** [comment]
One genome should be ok. The gene file list you must provide is not the "short" one, the "short.fasta" should be inside a "short" folder, while your main gene fasta files on the main folder. Something like:

chewBBACA/schema_seed/gi_57158257_dbj_AP006725.1_:1002380-1003105.fasta
chewBBACA/schema_seed/gi_57158257_dbj_AP006725.1_:1003225-1004076.fasta

and inside your "schema_seed" folder a subfolder called "short", where you will have the matching "short" files

**Comment by andrewdavis3** [comment]
ahh thanks

I was still running into issues trying to read the file even though I created all my files on a mac but I just ended up flipping rstrip('\n') to rstrip() that seemed to help. Thanks again!

**Comment by mickaelsilva** [comment]
I had never tried to run it on a mac, so thanks for the feedback. Let me know if you run on some other issues or any other questions/suggestions.
