### ISSUE TITLE
BBACA.py bug

### ISSUE THREAD

**Issue by mariamiskander** [mickaelsilva/chewBBACA#2]
Running BBACA.py gives this syntax error: 

```
File "BBACA.py", line 60
    print str(e)+" "+str(genomeFile)
            ^
SyntaxError: invalid syntax
```

Thanks :)

**Comment by mickaelsilva** [comment]
Hello Mariam,

When was the last time you pulled the repository? I was not able to reproduce the error with the last version (uploaded 3 days ago).

**Comment by mariamiskander** [comment]
Hi Mickael,

I pulled it today so I had the newest version. When I got the error I checked out a commit from November 25th and it worked. I will investigate a bit more just in case it's a problem on my end. 

Thanks

**Comment by mickaelsilva** [comment]
Can you try to pull again and check if it works now?
Which python version are you using btw?

**Comment by mariamiskander** [comment]
Ah I was using python 3. I switched to 2.7 and it works perfectly. Thanks Mickael :)
